//
// RepositoryList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct RepositoryList: Codable {

    public var totalCount: Int?
    public var incompleteResults: Bool?
    public var items: [Repository]?

    public init(totalCount: Int?, incompleteResults: Bool?, items: [Repository]?) {
        self.totalCount = totalCount
        self.incompleteResults = incompleteResults
        self.items = items
    }

    public enum CodingKeys: String, CodingKey { 
        case totalCount = "total_count"
        case incompleteResults = "incomplete_results"
        case items
    }


}

